-- MySQL Script generated by MySQL Workbench
-- Thu Sep  9 22:28:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sudoku
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sudoku
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sudoku` DEFAULT CHARACTER SET utf8 ;
USE `sudoku` ;

-- -----------------------------------------------------
-- Table `sudoku`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku`.`users` (
  `id` varchar(45)  NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `experience` INT NOT NULL,
  `sudokuCount` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sudoku`.`sudoku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku`.`sud` (
  `id` varchar(45)  NOT NULL,
  `numbers` JSON NOT NULL,
  `trueVariant` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `sudoku`.`solved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sudoku`.`solved` (
  `id` INT NOT NULL,
  `userId` varchar(45) NOT NULL,
  `sudokuId` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `toUsers_idx` (`userId` ASC) VISIBLE,
  INDEX `toSudoku_idx` (`sudokuId` ASC) VISIBLE,
  CONSTRAINT `toUsers`
    FOREIGN KEY (`userId`)
    REFERENCES `sudoku`.`users` (`id`)
    ON DELETE cascade
    ON UPDATE Cascade,
  CONSTRAINT `toSudoku`
    FOREIGN KEY (`sudokuId`)
    REFERENCES `sudoku`.`sud` (`id`)
	ON DELETE cascade
    ON UPDATE Cascade)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;